# This is a basic workflow to help you get started with Actions

name: Go Release Binaries
  # You may pin to the exact commit or the version.
  uses: wangyoucao577/go-release-action@v1.25
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    # GOOS: one of darwin, freebsd, linux, and so on.
    goos: linux 
    # GOARCH: one of 386, amd64, arm, s390x, and so on.
    goarch: amd64 
    ldflags: "-w -s"
    # Where to run `go build .`
    project_path: bin
    # Specify another binary name if do not want to use repository basename
    binary_name: dirx_amd64
    # How many times retrying if upload fails.
    retry: # optional, default is 3
