# This is a basic workflow to help you get started with Actions
on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64]
        exclude:  
          # windows/386 and darwin/386 seems useless 
          - goarch: "386"
            goos: windows 
          - goarch: "386"
            goos: darwin 
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.25
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos:  ${{ matrix.goos }}
        goarch:  ${{ matrix.goarch }}
        ldflags: "-w -s"
        # Where to run `go build .`
        project_path: bin
        # Specify another binary name if do not want to use repository basename
        binary_name: dirx
