# This is a basic workflow to help you get started with Actions
on:
  release:
    types: [created]

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.25
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux 
        goarch: amd64 
        ldflags: "-w -s"
        # Where to run `go build .`
        project_path: bin
        # Specify another binary name if do not want to use repository basename
        binary_name: dirx
